name: Setup Firebase Environment

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    # このワークフローは他のワークフローから呼び出すことができます

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          mkdir -p apps/web
          echo "VITE_FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY || 'dummy-key-for-ci' }}" >> apps/web/.env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN || 'project-id.firebaseapp.com' }}" >> apps/web/.env
          echo "VITE_FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID || 'project-id' }}" >> apps/web/.env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET || 'project-id.appspot.com' }}" >> apps/web/.env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID || '123456789' }}" >> apps/web/.env
          echo "VITE_FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID || '1:123456789:web:abc123' }}" >> apps/web/.env
      
      # このステップの後、他のジョブ（ビルド、テストなど）が実行できます