name: Setup Firebase Environment

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    # このワークフローは他のワークフローから呼び出すことができます

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Firebase environment variables
        env:
          FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
        run: |
          if [ -z "$FIREBASE_API_KEY" ] || \
             [ -z "$FIREBASE_AUTH_DOMAIN" ] || \
             [ -z "$FIREBASE_PROJECT_ID" ] || \
             [ -z "$FIREBASE_STORAGE_BUCKET" ] || \
             [ -z "$FIREBASE_MESSAGING_SENDER_ID" ] || \
             [ -z "$FIREBASE_APP_ID" ]; then
            echo "ERROR: Required Firebase environment variables are not set!"
            echo "Please set all required Firebase environment variables in GitHub repository variables."
            exit 1
          fi
          
          # 確認のために変数の状態を出力（APIキーは一部マスク）
          echo "Firebase API Key: ${FIREBASE_API_KEY:0:5}..."
          echo "Firebase Auth Domain: $FIREBASE_AUTH_DOMAIN"
          echo "Firebase Project ID: $FIREBASE_PROJECT_ID"
          
      - name: Create .env file
        env:
          FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
        run: |
          mkdir -p apps/web
          echo "VITE_FIREBASE_API_KEY=$FIREBASE_API_KEY" >> apps/web/.env
          echo "VITE_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> apps/web/.env
          echo "VITE_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> apps/web/.env
          echo "VITE_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> apps/web/.env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> apps/web/.env
          echo "VITE_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> apps/web/.env
      
      # このステップの後、他のジョブ（ビルド、テストなど）が実行できます