name: Setup Firebase Environment

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    # このワークフローは他のワークフローから呼び出すことができます

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Firebase environment variables
        run: |
          if [ -z "${{ vars.FIREBASE_API_KEY }}" ] || \
             [ -z "${{ vars.FIREBASE_AUTH_DOMAIN }}" ] || \
             [ -z "${{ vars.FIREBASE_PROJECT_ID }}" ] || \
             [ -z "${{ vars.FIREBASE_STORAGE_BUCKET }}" ] || \
             [ -z "${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" ] || \
             [ -z "${{ vars.FIREBASE_APP_ID }}" ]; then
            echo "ERROR: Required Firebase environment variables are not set!"
            echo "Please set all required Firebase environment variables in GitHub repository variables."
            exit 1
          fi
          
      - name: Create .env file
        run: |
          mkdir -p apps/web
          echo "VITE_FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY }}" >> apps/web/.env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }}" >> apps/web/.env
          echo "VITE_FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}" >> apps/web/.env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}" >> apps/web/.env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" >> apps/web/.env
          echo "VITE_FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }}" >> apps/web/.env
      
      # このステップの後、他のジョブ（ビルド、テストなど）が実行できます